services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: controller
    ports:
      - "8080:8080"
    environment:
      - SCRAPER_BASE_URL=${SCRAPER_BASE_URL:-http://scraper-api:8081}
      - TEXTANALYZER_BASE_URL=${TEXTANALYZER_BASE_URL:-http://textanalyzer:8082}
      - CONTROLLER_PORT=8080
      - DATABASE_PATH=/app/data/controller.db
    volumes:
      - controller-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  controller-data:
    driver: local

networks:
  default:
    name: controller-network
